---
  - name: CI testing
    on:
      pull_request:
      push:
        branches:
          - main
    jobs:
      test:
        name: Testing demo
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: Install dependency
          run: pip3 Install yamllint ansible-lint
        - name: Lint Ansible Playbook
          uses: ansible/ansible-lint-action@master
